### ISSUE TITLE
Merge the branch used in xvf3800 to develop

### ISSUE THREAD

**Issue by shuchitak** [xmos/xcore_iot#591]
XVF3800 currently uses the branch https://github.com/xmos/xcore_sdk/tree/feature/xvf3800_testing which was branched off from the commit 008b93a43081301e5363fea8b0f025a4feb85451 and has fixes we've made since then as part of sw_xvf3800 development. 
This branch needs to be merged to xcore_sdk develop and sw_xvf3800 needs to be updated to use the latest xcore_sdk.

**Comment by keithm-xmos** [comment]
Can this issue be closed now that sw_xvf3800 no longer depends on the the xcore_sdk repository?

**Comment by keithm-xmos** [comment]
I should have tagged @shuchitak.

Can this issue be closed now that sw_xvf3800 no longer depends on the the xcore_sdk repository?

**Comment by shuchitak** [comment]
@keithm-xmos, yes, I'll close this.
