### ISSUE TITLE
Unable to find "infr_scripts_py" project 

### ISSUE THREAD

**Issue by VirgilYP** [xmos/xcore_iot#599]
System information:

OS: ubuntu22.04
SDK version tag or commit SHA: 6e5625dd124ff5b9765215bbdf21a8189c5a872b

Problem description:
I am attempting to use the CI architecture in XCORE_SDK for automated testing, but I am encountering issues with dependency installation. Specifically, when running the command "pip install --src infr -r infr_requirements.txt", I am receiving an error indicating that the repository cannot be found. Additionally, upon checking the XCORE_SDK GitHub page, I noticed that a project named "infr_scripts_py" could not be found.

Steps taken before encountering the problem:
I cloned the "infr_scripts_py.git" repository from the XCORE_SDK GitHub page using the command "git clone ssh://****@github.com/xmos/infr_scripts_py.git (to revision develop) to ./infr/infr-scripts-py".

Other information or logs:
Cloning ssh://@github.com/xmos/infr_scripts_py.git (to revision develop) to ./infr/infr-scripts-py
Running command git clone --filter=blob:none --quiet 'ssh://@github.com/xmos/infr_scripts_py.git' /home/lyp/test/xcore_sdk/tools/ci/infr/infr-scripts-py
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

**Comment by keithm-xmos** [comment]
Hi @VirgilYP,

I apologize that you are experiencing this issue.  The `infr_scripts_py` repository is private so you will not be able to clone it.  Also, instructions in the `tools/ci/README.md` file are not used in the CI system.  

Lastly, please not that the `xcore_sdk` is undergoing significant refactoring so the develop `branch` may be unstable.  It is recommend that users remain on release tags.
